# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vpism/resources/load.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 741)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("* {\n"
"    background-color: #181A24;   /* Main dark background */\n"
"    color: #E8ECEF;              /* Light text for contrast */\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: #181A24;   /* Same as window background */\n"
"    color: #E8ECEF;              /* Text stays readable */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #181A24;   /* Flat button look */\n"
"    color: #E8ECEF;              /* Button text */\n"
"    border: none;   /* Subtle border */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E6696;   /* Accent on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8A9BC0;   /* Lighter accent when pressed */\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.image_frame = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_frame.sizePolicy().hasHeightForWidth())
        self.image_frame.setSizePolicy(sizePolicy)
        self.image_frame.setText("")
        self.image_frame.setPixmap(QtGui.QPixmap("vpism/resources/../../../../../home/marwan/Downloads/clipboard_image.png"))
        self.image_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.image_frame.setObjectName("image_frame")
        self.verticalLayout_2.addWidget(self.image_frame)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setStyleSheet("/* Special Close Button */\n"
"QPushButton {\n"
"    background-color: #b22222;   /* Firebrick red */\n"
"    color: #ffffff;\n"
"    border: 1px solid #8b1a1a;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #dc143c;   /* Crimson hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8b0000;   /* Dark red pressed */\n"
"}")
        self.close_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/icons/power_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon)
        self.close_button.setIconSize(QtCore.QSize(32, 32))
        self.close_button.setObjectName("close_button")
        self.verticalLayout.addWidget(self.close_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.brightness_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightness_button.sizePolicy().hasHeightForWidth())
        self.brightness_button.setSizePolicy(sizePolicy)
        self.brightness_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgs/icons/brightness.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brightness_button.setIcon(icon1)
        self.brightness_button.setIconSize(QtCore.QSize(32, 32))
        self.brightness_button.setObjectName("brightness_button")
        self.verticalLayout.addWidget(self.brightness_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.viens_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viens_button.sizePolicy().hasHeightForWidth())
        self.viens_button.setSizePolicy(sizePolicy)
        self.viens_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imgs/icons/veins.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viens_button.setIcon(icon2)
        self.viens_button.setIconSize(QtCore.QSize(32, 32))
        self.viens_button.setObjectName("viens_button")
        self.verticalLayout.addWidget(self.viens_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.scale_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_button.sizePolicy().hasHeightForWidth())
        self.scale_button.setSizePolicy(sizePolicy)
        self.scale_button.setMinimumSize(QtCore.QSize(46, 42))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.scale_button.setFont(font)
        self.scale_button.setIconSize(QtCore.QSize(32, 32))
        self.scale_button.setObjectName("scale_button")
        self.verticalLayout.addWidget(self.scale_button)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.save_showfiles_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_showfiles_button.sizePolicy().hasHeightForWidth())
        self.save_showfiles_button.setSizePolicy(sizePolicy)
        self.save_showfiles_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imgs/icons/files.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_showfiles_button.setIcon(icon3)
        self.save_showfiles_button.setIconSize(QtCore.QSize(32, 32))
        self.save_showfiles_button.setObjectName("save_showfiles_button")
        self.verticalLayout.addWidget(self.save_showfiles_button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.play_pause_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_pause_button.sizePolicy().hasHeightForWidth())
        self.play_pause_button.setSizePolicy(sizePolicy)
        self.play_pause_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/imgs/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pause_button.setIcon(icon4)
        self.play_pause_button.setIconSize(QtCore.QSize(32, 32))
        self.play_pause_button.setObjectName("play_pause_button")
        self.verticalLayout.addWidget(self.play_pause_button)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.rotate_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_button.sizePolicy().hasHeightForWidth())
        self.rotate_button.setSizePolicy(sizePolicy)
        self.rotate_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/imgs/icons/rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotate_button.setIcon(icon5)
        self.rotate_button.setIconSize(QtCore.QSize(32, 32))
        self.rotate_button.setObjectName("rotate_button")
        self.verticalLayout.addWidget(self.rotate_button)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "veins detection"))
        self.scale_button.setText(_translate("MainWindow", "x1"))
from . import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
